logging:
  level:
    org:
      springframework:
        cloud:
          kubernetes: DEBUG
spring:
  application:
    name: configmap-server-kubernetes
management:
  endpoint:
    web:
      exposure:
        include: info,refresh,keepalive,health